model:
  name: "bert-base-uncased"
  max_num_labels: 6

training:
  num_steps: 1000 
  batch_size: 32
  learning_rate: 2e-5
  optimizer: "adamw"
  epochs : 20

data:
  synthetic_data_path: "data/synthetic_data.json"